FROM  nvidia/cuda:11.7.0-runtime-ubuntu22.04
LABEL MAINTAINER="chatGLM"

RUN mkdir -p /data/workdir/software/
ENV WORKING_DIR /data/workdir/langchian_chatglm
COPY . /data/workdir/langchian_chatglm
WORKDIR /data/workdir/langchian_chatglm


# wget -c -N https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh --no-check-certificate && \
#     bash Miniconda3-py310_23.1.0-1-Linux-x86_64.sh -b -p /data/workdir/software/miniconda3 && ln -sf /data/workdir/software/miniconda3 /usr/local/miniconda3 && \
#     rm -rf Miniconda3-py310_23.1.0-1-Linux-x86_64.sh


RUN sed -i 's/security.ubuntu.com/mirrors.bfsu.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/archive.ubuntu.com/mirrors.bfsu.edu.cn/g' /etc/apt/sources.list


RUN apt-get update -y && apt-get install python3 python3-pip curl git-lfs -y && apt-get clean
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && rm -rf get-pip.py

RUN pip3 install -r requirements.txt --trusted-host https://mirrors.tencent.com -i https://mirrors.tencent.com/pypi/simple \
    && rm -rf `pip3 cache dir`

CMD ["python3","-u", "webui.py"]
# docker login --username=rapid7@actanble registry.cn-shenzhen.aliyuncs.com --password 123.
